spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PGURL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false